spring:
  datasource:
    drive-class-name: org.h2.Drive
    url: jdbc:h2:mem:superticket
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /documentation
    disable-swagger-default-url: true

security:
  token:
    secret-user: SUPERTICKET@2024